[package]
name = "apple-bot"
version = "0.1.1"
edition = "2024"
description = "A NapCat based QQ bot implemented in Rust"
keywords = ["qq", "bot", "napcat", "chatbot"]
authors = ["cclvi256 <i@cclvi.cc>"]
license = "LGPL-3.0-or-later"
homepage = "https://github.com/cclvi256/apple-bot"
repository = "https://github.com/cclvi256/apple-bot"
readme = "README.md"

[lib]
name = "apple_bot"
path = "src/lib.rs"

[[bin]]
name = "apple-bot"
path = "src/main.rs"

[dependencies]
axum = "0.8.8"
tokio = { version = "1.51.1", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
