# pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: cider-bot
spec:
  containers:
    - name: napcat
      image: docker.io/mlikiowa/napcat-docker:latest
      env:
        - name: NAPCAT_UID
          value: "0"
        - name: NAPCAT_GID
          value: "0"
      ports:
        - containerPort: 3000
          hostPort: 3000
        - containerPort: 3001
          hostPort: 3001
        - containerPort: 6099
          hostPort: 6099
      volumeMounts:
        - name: qq-data
          mountPath: /app/.config/QQ
        - name: napcat-config
          mountPath: /app/napcat/config
        - name: napcat-plugins
          mountPath: /app/napcat/plugins
    # - name: cider-bot
    #   image: ghcr.io/cclvi256/cider-bot:latest
    #   ports:
    #     - containerPort: 8888
    #       hostPort: 8888
  volumes:
    - name: qq-data
      persistentVolumeClaim:
        claimName: cider-bot-qq-data
    - name: napcat-config
      persistentVolumeClaim:
        claimName: cider-bot-napcat-config
    - name: napcat-plugins
      persistentVolumeClaim:
        claimName: cider-bot-napcat-plugins
