name: "Build and Push Container Image to GitHub Container Registry (ghcr.io)"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build & Push Container Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Login to ghcr.io
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | buildah login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
      - name: Generate Image ID
        id: generate-image-id
        run: |
          IMAGE_ID=$(echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          echo "image_id=$IMAGE_ID" >> $GITHUB_OUTPUT
      - name: Build Container Image with Buildah
        id: build-image
        run: |
          IMAGE_ID="${{ steps.generate-image-id.outputs.image_id }}"
          VERSION_TAG="${{ github.ref_name }}"
          echo "Building image: $IMAGE_ID:latest"
          buildah build \
            -f Containerfile \
            -t $IMAGE_ID:latest \
            .
          echo "Tagging image with version: $VERSION_TAG"
          buildah tag $IMAGE_ID:latest $IMAGE_ID:$VERSION_TAG
          echo "version_tag=$VERSION_TAG" >> $GITHUB_OUTPUT
      - name: Push to ghcr.io
        run: |
          IMAGE_ID="${{ steps.generate-image-id.outputs.image_id }}"
          VERSION_TAG="${{ steps.build-image.outputs.version_tag }}"
          echo "Pushing $IMAGE_ID:$VERSION_TAG"
          buildah push $IMAGE_ID:$VERSION_TAG
          echo "Pushing $IMAGE_ID:latest"
          buildah push $IMAGE_ID:latest
